[rules]
missing-license = { level = "off", source-shasum = "26d98ee9bf18a6eba0d3f855ddec31dbe857667d269bc0b6017335572f85bbcb" }
license-not-found = { level = "off", source-shasum = "26d98ee9bf18a6eba0d3f855ddec31dbe857667d269bc0b6017335572f85bbcb" }
unused-runpath-entry = {ignored_files=["lib/*"]}
