[rules]
license-not-found = {level = "off", source-shasum = "aa54850ebda5064c72cd4ec2d9b056c294252991486350d9a97ab2a6dfdfaf12"}
missing-license = {level = "off", source-shasum = "aa54850ebda5064c72cd4ec2d9b056c294252991486350d9a97ab2a6dfdfaf12"}
unused-dependency = {ignored_packages = [
    "core/bash-static",
    "core/hab-ld-wrapper"
]}
unused-runpath-entry = {level = "off"}
