[rules]
missing-license = { level = "off", source-shasum = "67fc1a4030d08ee877a4867d3dcab35828148f87e1fd05da6db585ed5a166bd4" }
license-not-found = { level = "off", source-shasum = "67fc1a4030d08ee877a4867d3dcab35828148f87e1fd05da6db585ed5a166bd4" }
unused-dependency = { ignored_packages = [
    "core/bash-static",
    "core/hab-ld-wrapper",
] }