[rules]
license-not-found = {level = "off", source-shasum = "da24a84fef220102dd24042df06fdea851c2614a5377f86effa28f33b7b16148"}
missing-license = {level = "off", source-shasum = "da24a84fef220102dd24042df06fdea851c2614a5377f86effa28f33b7b16148"}
unused-dependency = {ignored_packages = [
    "core/bash-static",
    "core/hab-ld-wrapper"
]}
unused-runpath-entry = {level = "off"}
