[rules]
missing-license = { level = "off", source-shasum = "f14c83cfebcc9427f2c3cea7258bd90df972d92eb26752da4ddad81c87a0faa4" }
license-not-found = { level = "off", source-shasum = "f14c83cfebcc9427f2c3cea7258bd90df972d92eb26752da4ddad81c87a0faa4" }
# m4 is used at runtime
unused-dependency = { ignored_packages = ["core/m4"] }
