[rules]
license-not-found = {level = "off", source-shasum = "965c7f4be96fb64f9581852c58c4f05c3812d4ad823c0f3e2bdfe777c162f999"}
missing-license = {level = "off", source-shasum = "965c7f4be96fb64f9581852c58c4f05c3812d4ad823c0f3e2bdfe777c162f999"}
host-script-interpreter = {ignored_files = ["share/contrib/*"]}
missing-runpath-entry-dependency = {ignored_files = ["bin/*"]}
script-interpreter-not-found = {ignored_files = ["hooks/*"]}
unused-dependency = {ignored_packages = ["core/bash", "core/perl", "core/grep", "core/gawk"]}
unused-runpath-entry = {ignored_files = ["bin/*", "lib/*"]}
