[rules]
license-not-found = {level = "off", source-shasum = "9a93b2b7dfdac77ceba5a558a580e74667dd6fede4585b91eefb60f03b72df23"}
missing-license = {level = "off", source-shasum = "9a93b2b7dfdac77ceba5a558a580e74667dd6fede4585b91eefb60f03b72df23"}
unused-runpath-entry = {level = "off"}
