[rules]
license-not-found = {level = "off", source-shasum = "b2809ca53124c19c60f42bf627736eae011afdcc205bb48270a5ee9a38191531"}
unused-runpath-entry = {ignored_files = ["lib/libsqlite3.so*", "bin/sqlite3"]}