[rules]
license-not-found = {level = "off", source-shasum = "7ea3297ea5969b5d25a5dd8d47f2443cda88e9ee746301f6e1e1426f8a6abc8f"}
missing-license = {level = "off", source-shasum = "7ea3297ea5969b5d25a5dd8d47f2443cda88e9ee746301f6e1e1426f8a6abc8f"}
host-script-interpreter = {level = "off"}
unused-runpath-entry = "off"
