[rules]
# Parallel has multiple environment files for different shells
env-script-interpreter-not-found = {ignored_files = [
    "bin/env_parallel*",
    "bin/parset"
]}
license-not-found = {level = "off", source-shasum = "4da90c7bec18a94431b4e3db49dd563f65cf20ceafd245f7cc7b42ef8bf8597f"}
missing-license = {level = "off", source-shasum = "4da90c7bec18a94431b4e3db49dd563f65cf20ceafd245f7cc7b42ef8bf8597f"}
# The binaries in procps-ng are used at runtime by parallel
unused-dependency = {ignored_packages = ["core/procps-ng"]}
