[rules]
license-not-found = {level = "off", source-shasum = "ca43bf261d4d392cff20dfae440836603bf009fce24fdc9b2697d837a2239d4f"}
missing-license = {level = "off", source-shasum = "ca43bf261d4d392cff20dfae440836603bf009fce24fdc9b2697d837a2239d4f"}
unused-runpath-entry = {ignored_files = ["bin/*", "lib/*"]}
