[rules]
license-not-found = {level = "off", source-shasum = "c95da32f440378d7751dd95533186f7fc05ceb4fb65eb5b85234e6299eb9838e"}
missing-license = {level = "off", source-shasum = "c95da32f440378d7751dd95533186f7fc05ceb4fb65eb5b85234e6299eb9838e"}
# hab-cc-wrapper is used at runtime
unused-dependency = {ignored_packages = [
    "core/hab-cc-wrapper"
]}
unused-runpath-entry = {level = "off"}
