pkg_name=linux-pam
pkg_origin=core
pkg_version="1.3.1"
pkg_license=('BSD-3-Clause')
pkg_maintainer="The Habitat Maintainers <humans@habitat.sh>"
pkg_description="Linux-PAM is a free implementation of the following DCE-RFC from Sunsoft."
pkg_upstream_url="http://www.linux-pam.org/"
pkg_source="https://github.com/linux-pam/linux-pam/releases/download/v${pkg_version}/Linux-PAM-${pkg_version}.tar.xz"
pkg_dirname="Linux-PAM-${pkg_version}"
pkg_shasum="eff47a4ecd833fbf18de9686632a70ee8d0794b79aecb217ebd0ce11db4cd0db"
pkg_deps=(core/glibc)
pkg_build_deps=(core/coreutils core/gcc core/make)
pkg_bin_dirs=(sbin)
pkg_include_dirs=(include)
pkg_lib_dirs=(lib)
