[rules]
license-not-found = {level = "off", source-shasum = "9a2a219da005a1730a39d1959a1c7cec619b1efb009b65be80ffc25bad299068"}
missing-license = {level = "off", source-shasum = "9a2a219da005a1730a39d1959a1c7cec619b1efb009b65be80ffc25bad299068"}
unused-runpath-entry = {level = "off"}
duplicate-runtime-binary = {level = "off"}