repos:
  - repo: https://github.com/scop/pre-commit-shfmt
    rev: v3.6.0-1
    hooks:
      - id: shfmt-docker
        exclude: (ld|cc)-wrapper.sh$
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0  # Use the ref you want to point at
    hooks:
    -   id: check-toml
  - repo: https://github.com/macisamuele/language-formatters-pre-commit-hooks
    rev: d2425a62376c2197448cce2f825d5a0c3926b862
    hooks:
    - id: pretty-format-toml
      args: [--autofix, --indent, "4"]