[rules]
unused-runpath-entry = {ignored_files = ["lib/gawk/{fork,rwarray,readfile,readdir,time,revoutput,ordchr,revtwoway,fnmatch,inplace,filefuncs,intdiv}.*", "libexec/awkpwcat", "libexec/awk/{grcat,pwcat}"]}
license-not-found = {level = "off", source-shasum = "378f8864ec21cfceaa048f7e1869ac9b4597b449087caf1eb55e440d30273336"}
missing-license = {level = "off", source-shasum = "378f8864ec21cfceaa048f7e1869ac9b4597b449087caf1eb55e440d30273336"}