# Accept connections on the specified port, default is 6379.
# If port 0 is specified Redis will not listen on a TCP socket.

# "always" "everysec" "no"
appendfsync = "everysec"
appendonly = "no"
# By default Redis listens for connections from all the network interfaces
# available on the server. It is possible to listen to just one or multiple
# interfaces using the "bind" configuration directive, followed by one or
# more IP addresses.
#
# Examples:
#
# bind = [ "192.168.1.100", "10.0.0.1" ]
# bind = [ "127.0.0.1" ]
# bind = [] - listen on all interfaces
bind = []
# Uncomment to enable syslog
# syslog-enabled = "yes"
# syslog-ident = "redis"
# syslog-facility = "local0"
databases = 16
dbfilename = "dump.rdb"
logfile = "\"\""
loglevel = "notice"
min-slaves-max-lag = false
min-slaves-to-write = false
no-appendfsync-on-rewrite = "no"
port = 6379
# By default, run Redis in protected mode.
protected-mode = "yes"
rbchecksum = "yes"
rbcompression = "yes"
repl-backlog-size = "1mb"
repl-backlog-ttl = "3600"
repl-disable-tcp-nodelay = "no"
repl-diskless-sync = "no"
repl-diskless-synx-delay = 5
repl-ping-slave-period = 10
repl-timeout = 60
requirepass = ""
slave-priority = "100"
slave-read-only = "yes"
# masterauth = ""
slave-serve-stale-data = "yes"
stop-writes-on-bgsave-error = "yes"
# TCP listen() backlog.
#
# In high requests-per-second environments you need an high backlog in order
# to avoid slow clients connections issues. Note that the Linux kernel
# will silently truncate it to the value of /proc/sys/net/core/somaxconn so
# make sure to raise both the value of somaxconn and tcp_max_syn_backlog
# in order to get the desired effect.
tcp-backlog = 511
tcp-keepalive = 0
timeout = 0

[[save]]
keys = 1
sec = 900

[[save]]
keys = 10
sec = 300

[[save]]
keys = 10000
sec = 60
