[rules]
# ignore examples with host script interpreters
host-script-interpreter = {ignored_files = ["*-example.{bash,tcsh}"]}
license-not-found = {level = "off", source-shasum = "890ae8ff810247bd19e274df76e8371d202cda01ad277681b0ea88eeaa00286b"}
missing-license = {level = "off", source-shasum = "890ae8ff810247bd19e274df76e8371d202cda01ad277681b0ea88eeaa00286b"}
unused-runpath-entry = {level = "off"}
