[rules]
license-not-found = { level = "off", source-shasum = "bd07b7e98839e0359842110525a3032fdb8eaf3a90bedde3dd1652d32d15cce5" }
missing-license = { level = "off", source-shasum = "bd07b7e98839e0359842110525a3032fdb8eaf3a90bedde3dd1652d32d15cce5" }
# ignore examples with host script interpreters
host-script-interpreter = { ignored_files = ["*-example.{bash,tcsh}"] }