[rules]
license-not-found = {level = "off", source-shasum = "64fdf23d734afad0dfe4077daca96ac51dcd697e68ae2d3d4ca6c45cb14e21ae"}
missing-license = {level = "off", source-shasum = "64fdf23d734afad0dfe4077daca96ac51dcd697e68ae2d3d4ca6c45cb14e21ae"}
unused-runpath-entry = {level = "off"}
unused-dependency = {level = "off"}