[rules]
missing-license = { level = "off", source-shasum = "ce650f829458af93a9e4e8cebea9d59e3d59132ade63c38decd6a10ecf3b5f97" }
license-not-found = { level = "off", source-shasum = "ce650f829458af93a9e4e8cebea9d59e3d59132ade63c38decd6a10ecf3b5f97" }
# We ignore scripts in the share folder
host-script-interpreter = {ignored_files = ["share/*"]}
missing-script-interpreter-dependency = {level = "off", ignored_files = ["share/*"]}
unused-runpath-entry = {ignored_files = ["bin/*"]}
