[rules]
# We ignore scripts in the share folder
host-script-interpreter = {ignored_files = ["share/*"]}
missing-script-interpreter-dependency = {level = "off", ignored_files = ["share/*"]}
unused-runpath-entry = {ignored_files = ["bin/*"]}
