[rules]
# We ignore scripts in the share folder
host-script-interpreter = {ignored_files = ["share/*"]}
license-not-found = {level = "off", source-shasum = "c75acdac8b80e664666663d3429efe1eb25be7f13db0bd3697a2d2a78dd1bb66"}
missing-license = {level = "off", source-shasum = "c75acdac8b80e664666663d3429efe1eb25be7f13db0bd3697a2d2a78dd1bb66"}
missing-script-interpreter-dependency = {level = "off", ignored_files = ["share/*"]}
unused-runpath-entry = {level = "off"}
