[rules]
license-not-found = {level = "off", source-shasum = "c4e0cbad57c90690cb813fb4663ef670b4d0f587d8171e2c42bd4c9245bd2758"}
missing-license = {level = "off", source-shasum = "c4e0cbad57c90690cb813fb4663ef670b4d0f587d8171e2c42bd4c9245bd2758"}
# These scripts are only used for tests and can be ignored
host-script-interpreter = {ignored_files = ["lib/python*/test/*", "lib/python*/lib2to3/**"]}
script-interpreter-not-found = {ignored_files = ["lib/python*/**"]}
unused-runpath-entry = {level = "off"}
