[rules]
license-not-found = {level = "off", source-shasum = "c4a6b75b7ed8f58ca48da830b9fa00ed96d668d3ab4b1f723dcf902f78bde77f"}
missing-license = {level = "off", source-shasum = "c4a6b75b7ed8f58ca48da830b9fa00ed96d668d3ab4b1f723dcf902f78bde77f"}
unused-runpath-entry = {level = "off"}
unused-dependency = {level = "off"}