[rules]
missing-license = { level = "off", source-shasum = "498d7cc1b4fb081904d87343febb73475cf771e424fb7e6141aff66013abc382" }
license-not-found = { level = "off", source-shasum = "498d7cc1b4fb081904d87343febb73475cf771e424fb7e6141aff66013abc382" }
unused-runpath-entry = { level = "off" }
unused-dependency = { level = "off" }
