[rules]
missing-license = {level = "off", source-shasum = "b24d0df852490d80791a228f18c2b75f24b1e6437e6e745f85364edab245f7fa"}
# Some rust files in the docs start with #![feature(...)] which is misinterpreted as a script
script-interpreter-not-found = {ignored_files = ["*.rs"]}
# The following dependencies are needed at runtime by Cargo for the associated reasons:
# 1. core/cacerts - Provides SSL certificates necessary for secure connections.
# 2. core/binutils - Supplies the 'ld' linker, utilized indirectly by Rust through gcc.
# 3. core/tzdata - Needed for the proper operation of the GNU C Library (glibc).
# 4. core/iana-etc - Also required for the functioning of glibc.
unused-dependency = {ignored_packages = [
    "core/{cacerts,binutils,tzdata,iana-etc}"
]}