[rules]
# ignore template's interpreters
env-script-interpreter-not-found = {ignored_files = [
    "lib/ruby/*/bundler/templates/*"
]}
license-not-found = {level = "off", source-shasum = "1a3c322e90cb22e5fba0b5d257bb2be9988affa3867eba7642ed981fdde895bb"}
missing-license = {level = "off", source-shasum = "1a3c322e90cb22e5fba0b5d257bb2be9988affa3867eba7642ed981fdde895bb"}
# core/ncurses: The paths for these packages get written into 'lib/ruby/<version>/<arch>/rbconfig.rb' and
# potentially affects further building of gems with the mkmf gem.
# core/nss-myhostname: This is apparently required at runtime, for some DNS lookup behaviour?
# https://github.com/habitat-sh/core-plans/commit/7761ccef724292640d14143ccb0cd5466e877fa5
unused-dependency = {ignored_packages = ["core/{ncurses,nss-myhostname,readline,openssl}"]}
unused-runpath-entry = {level = "off"}
host-script-interpreter = {level = "off"}
# we want ruby-stage1 binary as a base_ruby for building ruby33.so not adding as a run time dep.hence the below rule.
missing-runpath-entry-dependency = {ignored_files = ["lib/ruby/3.4.0+0/x86_64-linux/*" , 
"lib/ruby/gems/3.4.0+0/extensions/x86_64-linux/3.4.0+0/**/*.so" ,
"bin/ruby"]}
#ruby 33 adding src/build dir in run path for some shared files.so the below rule
bad-runpath-entry = {ignored_files = ["lib/ruby/3.4.0+0/x86_64-linux/enc/**/*.so"]}