[rules]
license-not-found = {level = "off", source-shasum = "c3e5e9fdd5004dcb542feda5ee4f0ff0744628baf8ed2dd5d66f8ca1197cb1a1"}
missing-license = {level = "off", source-shasum = "c3e5e9fdd5004dcb542feda5ee4f0ff0744628baf8ed2dd5d66f8ca1197cb1a1"}
unused-runpath-entry = {level = "off"}
