[rules]
# All these packages contain binaries used by tar at runtime
unused-dependency = {ignored_packages = ["core/{xz,zstd,bzip2,lzip,gzip,lzop,attr,acl}"]}
unused-runpath-entry = {level = "off"}
license-not-found = {level = "off", source-shasum = "14d55e32063ea9526e057fbf35fcabd53378e769787eff7919c3755b02d2b57e"}
missing-license = {level = "off", source-shasum = "14d55e32063ea9526e057fbf35fcabd53378e769787eff7919c3755b02d2b57e"}