address = "0.0.0.0"

cluster-signing-cert-file = ""
cluster-signing-key-file = ""

master = "http://127.0.0.1:8080"

root-ca-file = ""

service-account-private-key-file = ""
service-cluster-ip-range = "10.32.0.0/24"
