[rules]
license-not-found = {level = "off", source-shasum = "6d0eb3cfa9f92d947731cc75f1750356b3bdfc07ea020553daf6af1c768e0be2"}
missing-license = {level = "off", source-shasum = "6d0eb3cfa9f92d947731cc75f1750356b3bdfc07ea020553daf6af1c768e0be2"}
unused-runpath-entry = {ignored_files = ["lib/*"]}
