[rules]
license-not-found = {level = "off", source-shasum = "74b1081d21fff13ae4bd7c16e5d6e504a4c26f7cde1dca0d963a484174bbcacd"}
missing-license = {level = "off", source-shasum = "74b1081d21fff13ae4bd7c16e5d6e504a4c26f7cde1dca0d963a484174bbcacd"}
unused-runpath-entry = {level = "off"}
