[blobs]
path = ""

[bootstrap]
mlockall = "false"

[bulk]
request_timeout = "1m"

[cloud]

[cloud.aws]
access_key = ""
secret_key = ""

[cloud.azure]

[cloud.azure.management]

[cloud.azure.management.app]
id = ""
secret = ""

[cloud.azure.management.resourcegroup]
name = ""

[cloud.azure.management.subscription]
id = ""

[cloud.azure.management.tenant]
id = ""

[cluster]
name = "crate"

[cluster.graceful_stop]
force = "false"
min_availability = "primaries"
reallocate = "true"
timeout = "2h"

[cluster.info]

[cluster.info.update]
interval = "30s"

[cluster.routing]

[cluster.routing.allocation]
allow_rebalance = "indices_all_active"
cluster_concurrent_rebalance = "2"
enable = "all"
node_concurrent_recoveries = "2"
node_initial_primaries_recoveries = "4"

[cluster.routing.allocation.balance]
index = "0.5f"
primary = "0.05f"
shard = "0.45f"
threshold = "1.0f"

[cluster.routing.allocation.disk]
threshold_enabled = "true"

[cluster.routing.allocation.disk.watermark]
high = "90%"
low = "85%"

[discovery]
type = ""

[discovery.azure]
method = "vnet"

[discovery.ec2]
any_group = "true"
availability_zones = ""
endpoint = ""
groups = ""
host_type = "private_ip"
ping_timeput = "3s"

[discovery.srv]
query = ""
resolver = ""

[discovery.zen]
minimum_master_nodes = "1"
ping_timeout = "3s"
publish_timeout = "30s"

[discovery.zen.ping]

[discovery.zen.ping.unicast]
hosts = ""

[es]

[es.api]
enabled = "false"

[gateway]
expected_nodes = "-1"
recover_after_nodes = "-1"
recover_after_time = "5m"

[http]
port = 4200
publish_port = ""

[http.cors]
allow-credentials = "false"
allow-headers = "X-Requested-With, Content-Type, Content-Length"
allow-methods = "OPTIONS, HEAD, GET, POST, PUT, DELETE"
allow-origin = ""
enabled = "false"
max-age = "1728000"

[indices]

[indices.breaker]

[indices.breaker.fielddata]
limit = "60%"
overhead = "1.03"

[indices.breaker.query]
limit = "60%"
overhead = "1.09"

[indices.breaker.request]
limit = "40%"
overhead = "1.0"

[indices.recovery]
compress = "true"
concurrent_streams = "3"
file_chunk_size = "512kb"
max_bytes_per_sec = "40mb"
retry_activity_timeout = "15m"
retry_delay_network = "5s"
retry_delay_state_sync = "500ms"
retry_internal_action_timeout = "15m"
retry_internal_long_action_timeout = "30m"
translog_ops = "1000"
translog_size = "512kb"

[indices.store]

[indices.store.throttle]
max_bytes_per_sec = "20mb"
type = "merge"

[monitor]

[monitor.jvm]

[monitor.jvm.gc]

[monitor.jvm.gc.old]
debug = "1000ms"
info = "1000ms"
warn = "1000ms"

[monitor.jvm.gc.young]
debug = "1000ms"
info = "1000ms"
warn = "1000ms"

[network]
bind_host = ""
publish_host = ""

[node]
client = "false"
data = "true"
local = "false"
name = ""

[node.sql]
read_only = "false"

[path]
repo = ""

[plugins]
mandatory = ""

[psql]
port = 5432

[repositories]

[repositories.url]
allowed_urls = ""
supported_protocols = "http, https, ftp, file, jar"

[stats]
enabled = "false"
jobs_log_expiration = "0s"
jobs_log_size = "10000"
operations_log_expiration = "0s"
operations_log_size = "10000"

[stats.breaker]

[stats.breaker.log]

[stats.breaker.log.jobs]
limit = "5%"

[stats.breaker.log.operations]
limit = "5%"

[stats.service]
interval = "1h"

[transport]
publish_port = ""

[transport.tcp]
port = 4300
