[rules]
missing-license = { level = "off", source-shasum = "f01d58cd6d9d77fbdca9eb4bbd5ead1988228fdb73d6f7a201f5f8d6b118b469" }
license-not-found = { level = "off", source-shasum = "f01d58cd6d9d77fbdca9eb4bbd5ead1988228fdb73d6f7a201f5f8d6b118b469" }
# autoconf is used by automake at run time
unused-dependency = { ignored_packages = ["core/autoconf"] }