[rules]
missing-license = {level = "off", source-shasum = "aaf2fcb575cdf6491b98ab4829abf78a3dec8402b8b81efc8f23c00d443981bf"}
# TODO: Figure out why fips is unused
unused-dependency = {level = "off"}
