AUTH_KEY = 'alhpp&zxM!A_cLydfwAHt!{bRfK)_[&vBnomtndZ?K}5Sh:r]3-2J9q[QadNQ$;q'
AUTH_SALT = '+n-Z904uLwUf[fS(yJ`v2|LK+{H%-]rRo0i+vgj=ED^NDP4| +nq7c1V2LiqB[[j'
LOGGED_IN_KEY = '}-(@G8)ePCG)@1LPh*Y-TA?rDis,mp;Z,MzQDeiuzXT1$[NdBp8s2~G1927+ib-r'
LOGGED_IN_SALT = '#q-<*G+2|}dcwR.gqti+t}g[[KrfW`ez%?K._b+bd#y0g(w.9PWy>.Y=.@|=j|gP'
NONCE_KEY = '.0nUczGJ}q^S{/*1Pm;!U+H)XMw0?.+Rd{PkoXYSpMMrw1TEl]Ci`n)T-+p-<-*d'
NONCE_SALT = 'MZO22r,!91Pd=`K;IN-OO/5J^,KlInJQSYkl 5|J7^@-f1$xk:+]mwLUh%;DwS3D'
SECURE_AUTH_KEY = '?]r_TX`PH!<ZU_YKo3i1n}2;YQPKBVCQi@Rc%u|8kdCD#?j%[d/FN-L95@azrLrc'
SECURE_AUTH_SALT = 'W)#RiDm7m6Rj-cYTfPO&d?Pa>]&n8:rGzeL5]Zek|h4@)z:aV-.[[>6:y{2m}cw{'
