[rules]
# Ignore example script interpreters
host-script-interpreter = {ignored_files = ["share/doc/gettext/examples/*"]}
license-not-found = {level = "off", source-shasum = "c77d0da3102aec9c07f43671e60611ebff89a996ef159497ce8e59d075786b12"}
missing-license = {level = "off", source-shasum = "c77d0da3102aec9c07f43671e60611ebff89a996ef159497ce8e59d075786b12"}
# These are both false positives because the gcc-libs runpath is
# added to several libraries and binaries
missing-runpath-entry-dependency = {level = "off"}
script-interpreter-not-found = {ignored_files = [
    "share/doc/gettext/examples/*"
]}
# These packages are all used within scripts in gettext
unused-dependency = {ignored_packages = [
    "core/sed",
    "core/coreutils",
    "core/gzip",
    "core/sed",
    "core/xz",
    "core/bzip2"
]}
unused-runpath-entry = {level = "off"}
