[rules]
license-not-found = {level = "off", source-shasum = "8fc707f92a124b2aeb0f65dcf9ac8e27b2a305e7bcc4cc1b2fdf770eec0165bf"}
missing-license = {level = "off", source-shasum = "8fc707f92a124b2aeb0f65dcf9ac8e27b2a305e7bcc4cc1b2fdf770eec0165bf"}
# sed and gawk are used by scripts at runtime
# - lib/erlang/erts-<version>/bin/start_erl.src
unused-dependency = {ignored_packages = ["core/{sed,gawk}"]}
unused-runpath-entry = {level = "off"}
