[rules]
missing-license = {level = "off", source-shasum = "2c6a36c7b5a55accae063667ef3c55f2642e67476d96d355ff0acb13dbb47f09"}
missing-runpath-entry-dependency = {level = "off"}
# The core/gcc-base paths are unused and added by the build system
unused-runpath-entry = {level = "off"}
