[rules]
# grep, diffutils and coreutils are used in certain scripts of the gzip package
unused-dependency = {ignored_packages = [
    "core/coreutils",
    "core/diffutils",
    "core/grep",
    "core/less"
]}