[rules]
license-not-found = {level = "off", source-shasum = "ce5e03e519f637e1f814011ace35c4f87b33c0bbabeec35baf5fbd3479e91956"}
missing-license = {level = "off", source-shasum = "ce5e03e519f637e1f814011ace35c4f87b33c0bbabeec35baf5fbd3479e91956"}
# grep, diffutils and coreutils are used in certain scripts of the gzip package
unused-dependency = {ignored_packages = [
    "core/coreutils",
    "core/diffutils",
    "core/grep",
    "core/less"
]}
