[rules]
license-not-found = {level = "off", source-shasum = "7dc7129049cc7d61fef835381999cc5fabf9f4d84efb6d4936e6782f5c81fd24"}
missing-license = {level = "off", source-shasum = "7dc7129049cc7d61fef835381999cc5fabf9f4d84efb6d4936e6782f5c81fd24"}

# sed and gawk are used by scripts at runtime
# - lib/erlang/erts-<version>/bin/start_erl.src
# unused-dependency = {ignored_packages = ["core/{sed,gawk}"]}
# unused-runpath-entry = {level = "off"}
