[rules]
# This all deps are required by hab-backline
unused-dependency = { level = "off" }
# TODO: remove this after fixing binutils wrapper script interpreters
duplicate-runtime-binary = { level = "off" }