default_vhost="/"
default_user="guest"
default_pass="guest"

[default_permissions]
configure = ".*"
read = ".*"
write = ".*"

[listeners]
[listeners.tcp]
default=5672

[loopback_users]
guest=true

[management]
enabled=false
## One of 'basic', 'detailed' or 'none'. See
## http://rabbitmq.com/management.html#fine-stats for more details.
rates_mode="basic"

[management.listener]
port=15672
ip="0.0.0.0"
ssl=false

[erlang]
cookie=false

[rabbitmq.cluster]
enabled=false
