version: '2'
services:
  rabbitmq1:
    image: core/rabbitmq
    command: start core/rabbitmq --topology leader -I
  rabbitmq2:
    image: core/rabbitmq
    links:
      - rabbitmq1
    command: start core/rabbitmq --topology leader --peer rabbitmq1
  rabbitmq3:
    image: core/rabbitmq
    links:
      - rabbitmq1
    command: start core/rabbitmq --topology leader --peer rabbitmq1
