[host]

[host.localhost]
auto-deploy = true
unpack-wars = true

[host-manager]
localhost-only = false

[server]
ajp-port = "8009"
# Tomcat utilizes SecureRandom to provide random values for session ids.  When starting Tomcat under
# a newly created Habitat supervisor, Docker Container, etc., there is a long (> 50 seconds) delay
# where SecureRandom gathers enough entropy to return random values.  To avoid this, a non-blocking
# PRNG is passed to Tomcat for faster start up times.
catalina-opts = "-Djava.security.egd=file:/dev/./urandom"
# Configuration for the AJP connector
enable-ajp-connector = false
port = "8080"
redirect-port = "8443"
shutdown-port = "8005"

# [[userdbrealm.users]]
# username = "someuser"
# password = false
# roles = "manager-gui"
#
# This will be rendered in `conf_tomcat-users.xml` like this:
#
# <role rolename="manager-gui"/>
# <role rolename="manager-script"/>
# <role rolename="manager-jmx"/>
# <role rolename="manager-status"/>
# <user username="admin" password="super-secret-password" roles="manager-gui,manager-script,manager-jmx,manager-status"/>
[userdbrealm]
roles = []

[[userdbrealm.users]]
