[rules]
license-not-found = {level = "off", source-shasum = "349259af6821f730bc4ca3a0e6576efc75ba86e546d118629a5b75eb8ebc3a0b"}
missing-license = {level = "off", source-shasum = "349259af6821f730bc4ca3a0e6576efc75ba86e546d118629a5b75eb8ebc3a0b"}
unused-runpath-entry = {level = "off"}
env-script-interpreter-not-found = {level = "off"}