[rules]
missing-license = { level = "off", source-shasum = "8beb7590674957b931de6b7f81c530b85dc7c1ad8fbda015398bc1e8d1ce8ec5" }
license-not-found = { level = "off", source-shasum = "8beb7590674957b931de6b7f81c530b85dc7c1ad8fbda015398bc1e8d1ce8ec5" }
unused-runpath-entry = {ignored_files = ["lib/*"]}
