[rules]
license-not-found = {level = "off", source-shasum = "03e77afaf72942c7ac02ccebb19034e6e20f456dcf8dddadfeb572aa5ad3e451"}
missing-license = {level = "off", source-shasum = "03e77afaf72942c7ac02ccebb19034e6e20f456dcf8dddadfeb572aa5ad3e451"}
unused-runpath-entry = {level = "off"}
