[rules]
# Glibc unfortunately uses bashisms in the ldd, tzselect scripts so it's interpreter
# needs to be /bin/bash, but we haven't built bash yet. Since this package is
# only intended to be used within a studio where /bin/bash will be binlinked we let this pass
host-script-interpreter = {ignored_files = ["bin/tzselect", "bin/ldd"]}
license-not-found = {level = "off", source-shasum = "f77bd47cf8170c57365ae7bf86696c118adb3b120d3259c64c502d3dc1e2d926"}
missing-license = {level = "off", source-shasum = "f77bd47cf8170c57365ae7bf86696c118adb3b120d3259c64c502d3dc1e2d926"}
# Certain glibc headers include the linux headers, making it a runtime dependency
unused-dependency = {ignored_packages = ["core/linux-headers"]}
