version: '2'
services:
  zookeeper:
    image: core/zookeeper
    ports:
      - "2181:2181"
  kafka:
    image: core/kafka2
    links:
      - zookeeper
    command: start core/kafka2 --peer zookeeper --bind zookeeper:zookeeper.default
