[rules]
unused-runpath-entry = {ignored_files = ["bin/*"]}
# core/runc and core/netavark are required for habitat container exporter. Added by Matt Wrock
unused-dependency = {ignored_packages = ["core/{libassuan,libgpg-error,runc,netavark}"]}
