[rules]
license-not-found = {level = "off", source-shasum = "e4953e80415d039ccd33d34be74526a090fd585cf93f296cd9c593972504b6db"}
missing-license = {level = "off", source-shasum = "e4953e80415d039ccd33d34be74526a090fd585cf93f296cd9c593972504b6db"}
unused-runpath-entry = {level = "off"}
unused-dependency = {ignored_packages = ["core/{libxml2,geos,proj,bash,gdal,perl,libossp-uuid}"]}