[rules]
license-not-found = { level = "off", source-shasum = "49a7da83b0bdd9f46d04a04deec19c7767bb9a323e40c4781f89caf760b92c34" }
# These binaries and libraries have rpath added by the build system
unused-runpath-entry = { ignored_files = ["bin/expect", "lib/*/libexpect*.so"]}