[rules]
license-not-found = {level = "off", source-shasum = "9c4396cc829cfae319a6e2615202e82aad41372073482fce286fac78646d3ee4"}
missing-license = {level = "off", source-shasum = "9c4396cc829cfae319a6e2615202e82aad41372073482fce286fac78646d3ee4"}
# less and grep are used in script within the zstd package
unused-dependency = {ignored_packages = ["core/{less,grep}"]}
unused-runpath-entry = {level = "off"}
