[rules]
license-not-found = {level = "off", source-shasum = "f7de13462f7a82c29ab865820149e778cbfe01087b3a55b5332707abf9db4a6e"}
missing-license = {level = "off", source-shasum = "f7de13462f7a82c29ab865820149e778cbfe01087b3a55b5332707abf9db4a6e"}
# less and grep are used in script within the zstd package
unused-dependency = {ignored_packages = ["core/{less,grep}"]}
unused-runpath-entry = {level = "off"}
