[rules]
license-not-found = {level = "off", source-shasum = "87daefacd7958b4a69f88c6856dbd1634261963c414079d0c371f589cd66a2e3"}
missing-license = {level = "off", source-shasum = "87daefacd7958b4a69f88c6856dbd1634261963c414079d0c371f589cd66a2e3"}
# All these packages are used at runtime by scipts
unused-dependency = {ignored_packages = ["core/{expect,gawk,grep,coreutils,sed}"]}
