[rules]
# Ignore example scripts
host-script-interpreter = {ignored_files = ["share/doc/libxml2*"]}
license-not-found = {level = "off", source-shasum = "3727b078c360ec69fa869de14bd6f75d7ee8d36987b071e6928d4720a28df3a6"}
missing-license = {level = "off", source-shasum = "3727b078c360ec69fa869de14bd6f75d7ee8d36987b071e6928d4720a28df3a6"}
unused-runpath-entry = {level = "off"}
