[rules]
missing-license = { level = "off", source-shasum="c8d6681e38c56f172892c85ddc0852e1fd4b53b4209e7f4ebf17f7e2eae71d92" }
license-not-found = { level = "off", source-shasum="c8d6681e38c56f172892c85ddc0852e1fd4b53b4209e7f4ebf17f7e2eae71d92" }
# Ignore example scripts
host-script-interpreter = { ignored_files = ["share/doc/libxml2/python/examples/*"]}