[rules]
missing-license = { level = "off", source-shasum = "da24a84fef220102dd24042df06fdea851c2614a5377f86effa28f33b7b16148" }
# missing-runpath-entry-dependency = { ignored_files = [
#     "bin/gp-{archive,collect-app,display-src,display-text}",
#     "bin/gprofng",
#     "lib/gprofng/libgprofng.so*"
# ] }
# unused-runpath-entry = { ignored_files = [
#     "bin/gp-{archive,collect-app,display-src,display-text}",
#     "bin/gprofng",
#     "lib/gprofng/libgprofng.so*"
# ] }
unused-dependency = { ignored_packages = [
    "core/bash-static",
    "core/hab-ld-wrapper",
] }