[rules]
license-not-found = {level = "off", source-shasum = "48969323e94e3be3b03c6a132942dcba7ef8d545f2ad35401709019f696c3c4e"}
missing-license = {level = "off", source-shasum = "48969323e94e3be3b03c6a132942dcba7ef8d545f2ad35401709019f696c3c4e"}
unused-runpath-entry = {level = "off"}
host-script-interpreter = {level = "off"}
unused-dependency = {ignored_packages = ["core/db"]}
