[rules]
missing-license = { level = "off", source-shasum = "ac9c723f224969aee624bc34fd34c9e13f2a212d75c71c807de644bb46e112f6" }
license-not-found = { level = "off", source-shasum = "ac9c723f224969aee624bc34fd34c9e13f2a212d75c71c807de644bb46e112f6" }
host-elf-interpreter = "off"
library-dependency-not-found = "off"
host-script-interpreter = {level = "off"}
unexpected-elf-interpreter = "off"
unused-dependency = {ignored_packages = ["core/glibc"]}
