[rules]
license-not-found = {level = "off", source-shasum = "e6a2456907610639d73fc6a82bb10aa6fa02e2d03b24edacde34a16b6aa91080"}
missing-license = {level = "off", source-shasum = "e6a2456907610639d73fc6a82bb10aa6fa02e2d03b24edacde34a16b6aa91080"}
# The gcc-base lib folder is added to the built libraries by the build system
missing-runpath-entry-dependency = {ignored_files = ["lib/*"]}
unused-runpath-entry = {ignored_files = ["lib/*"]}
