[rules]
license-not-found = {level = "off", source-shasum = "feec1f2ce9c1b62798afd35a7d1b04cefdfa3a0a30ff3e75d6965ba8978c9144"}
missing-license = {level = "off", source-shasum = "feec1f2ce9c1b62798afd35a7d1b04cefdfa3a0a30ff3e75d6965ba8978c9144"}
unused-runpath-entry = {level = "off"}
