[rules]
license-not-found = {level = "off", source-shasum = "f525154adc5605e4ebf03d3e7ee8be4d7f3c7cf9df2c2244043406b6eefca2da"}
missing-license = {level = "off", source-shasum = "f525154adc5605e4ebf03d3e7ee8be4d7f3c7cf9df2c2244043406b6eefca2da"}
unused-runpath-entry = {level = "off"}
