[rules]
license-not-found = {level = "off", source-shasum = "97fc51ac2b085d4cde31ef4d2c3122c21abc217e9090a43a30fc5ec21684e059"}
missing-license = {level = "off", source-shasum = "97fc51ac2b085d4cde31ef4d2c3122c21abc217e9090a43a30fc5ec21684e059"}
# The core/gcc-libs runpath entry will always be added due to the ld-wrapper logic
unused-runpath-entry = {level = "off"}
