[rules]
missing-license = { level = "off", source-shasum = "30306e0c76e0f9f1f0de987cf1c82a5c21e1ce6568b9227f7da5b71cbea86c9d" }
license-not-found = { level = "off", source-shasum = "30306e0c76e0f9f1f0de987cf1c82a5c21e1ce6568b9227f7da5b71cbea86c9d" }
# The core/gcc-libs runpath entry will always be added due to the ld-wrapper logic
unused-runpath-entry = { level = "off" }