[rules]
license-not-found = {level = "off", source-shasum = "7628c55eb23768a2c799c018988d8f2ab48ee3d80f5e11259938f7a935f0d603"}
missing-license = {level = "off", source-shasum = "7628c55eb23768a2c799c018988d8f2ab48ee3d80f5e11259938f7a935f0d603"}
host-script-interpreter = {ignored_files = ["share/contrib/*"]}
missing-runpath-entry-dependency = {ignored_files = ["bin/*"]}
script-interpreter-not-found = {ignored_files = ["hooks/*"]}
unused-dependency = {ignored_packages = ["core/bash", "core/perl"]}
unused-runpath-entry = {ignored_files = ["bin/*", "lib/*"]}
