[rules]
bad-runpath-entry = {ignored_files = ["lib/*"]}
license-not-found = {level = "off", source-shasum = "8fc707f92a124b2aeb0f65dcf9ac8e27b2a305e7bcc4cc1b2fdf770eec0165bf"}
missing-license = {level = "off", source-shasum = "8fc707f92a124b2aeb0f65dcf9ac8e27b2a305e7bcc4cc1b2fdf770eec0165bf"}
script-interpreter-not-found = {ignored_files = ["lib/*"]}
unused-runpath-entry = {ignored_files = ["lib/*"]}
