[rules]
missing-license = { level = "off", source-shasum = "8fc707f92a124b2aeb0f65dcf9ac8e27b2a305e7bcc4cc1b2fdf770eec0165bf" }
license-not-found = { level = "off", source-shasum = "8fc707f92a124b2aeb0f65dcf9ac8e27b2a305e7bcc4cc1b2fdf770eec0165bf" }
unused-runpath-entry = {ignored_files=["lib/*"]}
bad-runpath-entry = {ignored_files=["lib/*"]}
script-interpreter-not-found = {ignored_files=["lib/*"]}
