[rules]
license-not-found = {level = "off", source-shasum = "1b79b381ac283d8b054368b335c408fedcb9b7144e0c07f531e3537d4328f3b3"}
missing-license = {level = "off", source-shasum = "1b79b381ac283d8b054368b335c408fedcb9b7144e0c07f531e3537d4328f3b3"}
unused-dependency = {level = "off"}
unused-runpath-entry = {level = "off"}
missing-runpath-entry-dependency = {level = "off"}