[rules]
missing-license = { level = "off", source-shasum = "90e337504031ef7d3077ab1a52ca8bac9b2f72bc454c95365a1cd1e0e81e06e9" }
license-not-found = { level = "off", source-shasum = "90e337504031ef7d3077ab1a52ca8bac9b2f72bc454c95365a1cd1e0e81e06e9" }
missing-runpath-entry-dependency = {ignored_files = ["lib/*.so*"]}
unused-runpath-entry = {ignored_files = ["lib/*.so*"]}
