[rules]
missing-license = { level = "off", source-shasum = "a2d2d38217092a7ed56635e34467f92f976b370e20182ad325edea6681a71d68" }
license-not-found = { level = "off", source-shasum = "a2d2d38217092a7ed56635e34467f92f976b370e20182ad325edea6681a71d68" }
# The $pkg_prefix/lib runpath is added by the build system
unused-runpath-entry = { ignored_files = [
    "lib/libicudata.so*",
    "sbin/escapesrc",
] }
