[rules]
# ignore template's interpreters
env-script-interpreter-not-found = {ignored_files = [
    "lib/ruby/*/bundler/templates/*"
]}
license-not-found = {level = "off", source-shasum = "0d0dafb859e76763432571a3109d1537d976266be3083445651dc68deed25c22"}
missing-license = {level = "off", source-shasum = "0d0dafb859e76763432571a3109d1537d976266be3083445651dc68deed25c22"}
# core/ncurses: The paths for these packages get written into 'lib/ruby/<version>/<arch>/rbconfig.rb' and
# potentially affects further building of gems with the mkmf gem.
# core/nss-myhostname: This is apparently required at runtime, for some DNS lookup behaviour?
# https://github.com/habitat-sh/core-plans/commit/7761ccef724292640d14143ccb0cd5466e877fa5
unused-dependency = {ignored_packages = ["core/{ncurses,nss-myhostname}"]}
unused-runpath-entry = {level = "off"}
