[rules]
license-not-found = {level = "off", source-shasum = "cc012bc860406dcf42f64431bcd3d2fa7560c02915a601aba9cd597a39329baa"}
missing-license = {level = "off", source-shasum = "cc012bc860406dcf42f64431bcd3d2fa7560c02915a601aba9cd597a39329baa"}
unused-dependency = {ignored_packages = ["core/openssl"]}
unused-runpath-entry = {ignored_files = ["lib/librhash.so.0"]}
