tags = []

# ================================ Logging ======================================
[logging]
to_files = true

[logging.files]
name = "metricbeat.log"
path = "var/logs"

[metricbeat]
max_start_delay = "10s"

# ============================  Config Reloading ===============================
[metricbeat.config]

[metricbeat.config.modules]

[metricbeat.config.modules.reload]
enabled = false

# ==========================  Modules configuration ============================
[[metricbeat.modules]]
metricsets = [
    "cpu",
    "load",
    "memory",
    "network",
    "process",
    "process_summary"
]
module = "system"
period = "10s"

[metricbeat.modules.process]

[metricbeat.modules.process.include_top_n]
by_cpu = 5
by_memory = 5

[[metricbeat.modules]]
metricsets = [
    "filesystem",
    "fsstat"
]
module = "system"
period = "1m"

[[metricbeat.modules.processors]]

[metricbeat.modules.processors."drop_event.when.regexp"]
"system.filesystem.mount_point" = "^/(sys|cgroup|proc|dev|etc|host|lib)($|/)"

[[metricbeat.modules]]
metricsets = ["uptime"]
module = "system"
period = "15m"

# ================================ Output ======================================
[output]

[output.elasticsearch]
hosts = ["localhost:9200"]
