[rules]
duplicate-runtime-binary = {level = "off"}
empty-top-level-directory = {level = "off"}
host-script-interpreter = {level = "off"}
unused-dependency = {level = "off"}
library-dependency-not-found = {level = "off"}