[rules]
# ignore interpreters in the cmake modules, not sure if this is ok
env-script-interpreter-not-found = {ignored_files = ["share/cmake-*/Modules/*"]}
host-script-interpreter = {ignored_files = ["share/cmake-3.25/Modules/Compiler/XL-Fortran/cpp"]}
license-not-found = {level = "off", source-shasum = "1c511d09516af493694ed9baf13c55947a36389674d657a2d5e0ccedc6b291d8"}
missing-license = {level = "off", source-shasum = "1c511d09516af493694ed9baf13c55947a36389674d657a2d5e0ccedc6b291d8"}
script-interpreter-not-found = {ignored_files = ["share/cmake-*/Modules/*"]}
unused-dependency = {ignored_packages = ["core/nghttp2", "core/bzip2", "core/openssl", "core/zstd", "core/xz"]}
unused-runpath-entry = {level = "off"}
