[rules]
license-not-found = {level = "off", source-shasum = "f3ac987522c00d33d44b323cae424e2cffcb4c63c6aa6cd1376edacbf1c36eb0"}
missing-license = {level = "off", source-shasum = "f3ac987522c00d33d44b323cae424e2cffcb4c63c6aa6cd1376edacbf1c36eb0"}
unused-runpath-entry = {level = "off"}
